spring.application.name=product
spring.config.import=optional:file:../../ecommerce-configmngmnt/product.yml,optional:configserver:http://localhost:8888

management.endpoints.web.exposure.include=health,info,refresh,env
management.endpoint.health.show-details=always
